@startuml

!include styles.puml
!include utils.puml
!include Configuration/Dialog.puml
!include Configuration/Table.puml
!include Configuration/Tree.puml
!include Configuration/API.puml

legend
    ** API array structure**
    ----
    print(ConfigurationTreeView)
    ----
    <b>ERM (Sqlite)
    print(ConfigurationTableView)
    ----
    <b>Edit-Dialog
    print(ConfigurationDialogView)
end legend


@enduml