@startuml
!definelong SearchAccordionView
{
    <b>Action Buttons:

   {[<&pus> New query]}

   ---
   {* Accordion Query #1 }
   {
       [X] Current extent
       { ^CSV^ | [ <&data-transfer-download>] |   [<&pincel> Edit] | [Style] |  }

       ---
       <b>Results:
       {#
           Action-Buttons | Name | Description
           { [<&star>] | [Locate] } | Name #2 | Beschreibung #1
           { [<&star>] | [Locate] } | Name #2 | Beschreibung #1
       }
   }
   ---
   {* Accordion Query #2 }
   ---
   {* Accordion Query #3 }

   {
       [ ] Current extent
       { ^XLS^ | [ Export] |   [Edit] | [Style] |  }


       <b>Results:
       {#
           Action-Buttons | Name | Description
           { [Favorite] | [Locate] } | Name #2 | Beschreibung #1
           { [Favorite] | [Locate] } | Name #2 | Beschreibung #1
           { [Favorite] | [Locate] } | Name #2 | Beschreibung #1
           { [Favorite] | [Locate] } | Name #2 | Beschreibung #1
           { [Favorite] | [Locate] } | Name #2 | Beschreibung #1
       }
       {*
          **Name**: Name #3 |
          **Beschreibung**: Details
       }
   }
}
!enddefinelong

!ifdef SALT
!else
    legend
    {{
    salt
       SearchAccordionView
    }}
    end legend
!endif
@enduml