@startuml
!definelong SearchAccordionView
{
    <b>Action Buttons:

   {[New query]}

   ---
   {* Accordion Query #1 }
   {
       [X] Current extent
       { ^CSV^ | [ Export] |   [Edit] | [Style] |  }

       ---
       <b>Results:
       {#
           Name | Description | Action-Buttons
           Name #2 | Beschreibung #1  | { [Favorite] | [Locate] }
           Name #2 | Beschreibung #2  | { [Favorite] | [Locate] }
       }
   }
   ---
   {* Accordion Query #2 }
   ---
   {* Accordion Query #3 }

   {
       [ ] Current extent
       { ^XLS^ | [ Export] |   [Edit] | [Style] |  }


       <b>Results:

       {#
           Name | Description          | Action-Buttons
           Name #3 | Beschreibung #1   | { [Favorite] | [Locate] }
           Name #2 | Beschreibung #2   | { [Favorite] | [Locate] }
           Name #3 | Beschreibung #3   | { [Favorite] | [Locate] }
       }
       {*
          **Name**: Name #3 |
          **Beschreibung**: Details
       }
   }
}
!enddefinelong

!ifdef SALT
!else
    legend
    {{
    salt
       SearchAccordionView
    }}
    end legend
!endif
@enduml