@startuml
!definelong EditQuerySourceView
{
    {+
          {/ General |  <b>Source | Fields | Conditions }
          ---
          {
            FeatureType | . | ^IPE^ | [<&menu>]
          }
          { [Cancel] | [ Save ]}
    }
}
!enddefinelong

!ifdef display
!else
    legend
    {{
    salt
       EditQuerySourceView
    }}
    end legend
!endif
@enduml