@startuml
!definelong EditQueryGeneralView
{
    {+
      {/ <b>General |  Source | Fields | Conditions | }
      --
      {
        Query-Name | "new query #1"
        Extent only | [X] yes
        Style | { ^Theme^ | [<&menu>] }

      }
      --
      {   [<&circle-x> Cancel] | [<&circle-check> Save ]}
    }
}
!enddefinelong

!ifdef display
!else
    legend
    {{
    salt
       EditQueryGeneralView
    }}
    end legend
!endif
@enduml