@startuml
package Mapbender <<Frame>> {
  package ConfigurationBundle <<frame>> {
    package entity <<frame>> {
        class Configuration <extends Entity> {
            + id: int
            + parentId: int
            -- key/value --
            + type: String
            + key: String
            + value: String

            -- history --
            + creationDate
            + user: User

            -- scope --
            + scope: String

            --
            + toArray() : array
            + getChildren() : array
            + getParent() : array
        }
    }

    package component <<frame>> {
        class ConfigurationComponent <extends ContainerAware> {
            + name: mapbender.configuration <<Symfony2 service>>
            --
            + getByid( id, scope = 'global' ) : Configuration
            + getBykey( key, parentId ) : Configuration
            + getByPath( path = "/", parentId = 0) : Configuration
            + getChildren( parentId = 0)
            -- Save --
            + save(value: Configuration) : Configuration
            + saveByParent ( parentId, values ) : Configuration
            + saveByKey( key, value, parentId = 0, type = null) : Configuration
            -- Remove --
            + remove(config: Configuration) : Configuration
            + removeById(id) : Configuration
        }
    }
  }
}

@enduml