@startuml
!include ../styles.puml
!include ../utils.puml
!include ConfigurationDialog.puml
!include ConfigurationTable.puml
!include ConfigurationTree.puml


package Mapbender <<Frame>> {
  package ConfigurationBundle <<frame>> {
    package entity <<frame>> {
        class Configuration {
            + id
            + parentid
            -- key/value --
            + type
            + key
            + value

            -- history --
            + creationdate
            + userid

            -- scope --
            + scope

            --
            + toArray() : array
            + getChildren() : array
            + getParent() : array
        }
    }

    legend
        ** API array structure**
        ----
        print(ConfigurationTreeView)
        ----
        <b>ERM (Sqlite)
        print(ConfigurationTableView)
        ----
        <b>Edit-Dialog
        print(ConfigurationDialogView)
    endlegend


    package component <<frame>> {
        class ConfigurationComponent {
            + getByid( id, scope = 'global' ) : Configuration
            + getBykey( key, parentId ) : Configuration
            + getByPath( path = "/", parentId = 0) : Configuration
            + getChildren( parentId = 0)
            -- Save --
            + save(value: Configuration) : Configuration
            + saveByParent ( parentId, values ) : Configuration
            + saveByKey( key, value, parentId = 0, type = null) : Configuration
            -- Remove --
            + remove(config: Configuration) : Configuration
            + removeById(id) : Configuration
            ---
        }
    }
  }
}

@enduml