@startuml

!definelong EditQueryConditionsView
{
    {+
        {/ General |  Source | Fields | <b>Conditions }
        ---
        {
           {
             <b>Add condition:
             {
                 Field       | ^name^
                 Operator    | ^LIKE^
                 Value       | "mustermann"

             }
             {[<&plus> Add condition]}

           } | . | {#
             <b>Field Name | <b>Operator | <b>Value      | <b>Action
             name        | LIKE          | "mustermann"  |[<&trash>]
             description | NOT LIKE      | "about"       |[<&trash>]
             km          | >=            | "20"          |[<&trash>]

           }
        }
        ---
        { [Cancel] | [ Save ]}
    }
}
!enddefinelong

!ifdef display
!else
    legend
    {{
    salt
       EditQueryConditionsView
    }}
    end legend
!endif
@enduml